module.exports = {
  apps: [
    {
      name: "cloud-orchestrator",
      script: "scripts/orchestrator.py",
      args: "--cloud",
      interpreter: "/opt/ai_employee/venv/bin/python",
      cwd: "/opt/ai_employee/platinum",
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      env_file: "/opt/ai_employee/platinum/.env",
      log_file: "/opt/ai_employee/platinum/Logs/pm2-orchestrator.log",
      error_file: "/opt/ai_employee/platinum/Logs/pm2-orchestrator-err.log",
      time: true,
    },
    {
      name: "gmail-watcher",
      script: "scripts/watch_gmail.py",
      args: "--api",
      interpreter: "/opt/ai_employee/venv/bin/python",
      cwd: "/opt/ai_employee/platinum",
      restart_delay: 10000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      env_file: "/opt/ai_employee/platinum/.env",
      log_file: "/opt/ai_employee/platinum/Logs/pm2-gmail.log",
      error_file: "/opt/ai_employee/platinum/Logs/pm2-gmail-err.log",
      time: true,
    },
    {
      name: "linkedin-poster",
      script: "scripts/linkedin_poster.py",
      interpreter: "/opt/ai_employee/venv/bin/python",
      cwd: "/opt/ai_employee/platinum",
      restart_delay: 10000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      env_file: "/opt/ai_employee/platinum/.env",
      log_file: "/opt/ai_employee/platinum/Logs/pm2-linkedin.log",
      error_file: "/opt/ai_employee/platinum/Logs/pm2-linkedin-err.log",
      time: true,
    },
    {
      name: "business-mcp",
      script: "mcp/business_mcp/server.py",
      interpreter: "/opt/ai_employee/venv/bin/python",
      cwd: "/opt/ai_employee/platinum",
      restart_delay: 5000,
      max_restarts: 20,
      autorestart: true,
      watch: false,
      env_file: "/opt/ai_employee/platinum/.env",
      log_file: "/opt/ai_employee/platinum/Logs/pm2-business-mcp.log",
      error_file: "/opt/ai_employee/platinum/Logs/pm2-business-mcp-err.log",
      time: true,
    },
    {
      name: "odoo-mcp",
      script: "mcp/odoo_mcp/server.py",
      interpreter: "/opt/ai_employee/venv/bin/python",
      cwd: "/opt/ai_employee/platinum",
      restart_delay: 5000,
      max_restarts: 20,
      autorestart: true,
      watch: false,
      env_file: "/opt/ai_employee/platinum/.env",
      log_file: "/opt/ai_employee/platinum/Logs/pm2-odoo-mcp.log",
      error_file: "/opt/ai_employee/platinum/Logs/pm2-odoo-mcp-err.log",
      time: true,
    },
    {
      // Watchdog: monitors all other processes, restarts if down, writes system_health.md
      name: "watchdog",
      script: "scripts/watchdog.py",
      args: "--daemon",
      interpreter: "/opt/ai_employee/venv/bin/python",
      cwd: "/opt/ai_employee/platinum",
      restart_delay: 15000,
      max_restarts: 50,        // watchdog itself must stay up — high restart budget
      autorestart: true,
      watch: false,
      env_file: "/opt/ai_employee/platinum/.env",
      log_file: "/opt/ai_employee/platinum/Logs/pm2-watchdog.log",
      error_file: "/opt/ai_employee/platinum/Logs/pm2-watchdog-err.log",
      time: true,
    },
    {
      // Approval workflow: scans Pending_Approval every 60s, moves files on decision/expiry
      name: "approval-workflow",
      script: "scripts/approval_workflow.py",
      args: "--daemon",
      interpreter: "/opt/ai_employee/venv/bin/python",
      cwd: "/opt/ai_employee/platinum",
      restart_delay: 5000,
      max_restarts: 20,
      autorestart: true,
      watch: false,
      env_file: "/opt/ai_employee/platinum/.env",
      log_file: "/opt/ai_employee/platinum/Logs/pm2-approval.log",
      error_file: "/opt/ai_employee/platinum/Logs/pm2-approval-err.log",
      time: true,
    },
  ],
};
