#!/usr/bin/env python3
"""
LinkedIn Post Generator
Generates professional LinkedIn post content from templates
and saves it as an approval request in AI_Employee_Vault/Needs_Approval/

Usage:
    python generate_post.py --template automation_success
    python generate_post.py --template company_update --topic "AI Employee launch"
    python generate_post.py --custom "Your custom post content here"
    python generate_post.py --list
"""

import argparse
import sys
import os
from pathlib import Path
from datetime import datetime


# ─── Templates ───────────────────────────────────────────────────────────────

TEMPLATES = {
    "automation_success": {
        "description": "Share an automation win",
        "content": """\
We just automated another part of our workflow and the results speak for themselves.

Our AI Employee now handles:
- Monitoring incoming tasks 24/7
- Generating action plans automatically
- Routing approvals to the right people
- Executing approved actions without manual input

The time savings are real. The errors are fewer. The team is happier.

If you are still doing repetitive work manually, ask yourself: could an AI Employee handle this?

The future of work is autonomous — not because it replaces people, but because it frees them for what matters.

#AI #Automation #FutureOfWork #ProductivityHack #AIEmployee"""
    },

    "company_update": {
        "description": "Share a company or project milestone",
        "content": """\
Big milestone reached.

We have been building in silence for months. Today, I am excited to share where we are.

Our AI Employee system is now live in Silver Tier:
- Autonomous task processing
- Human-in-the-loop approvals
- Gmail and LinkedIn integration
- 24/7 operation with rotating logs and deduplication

This is not just a tool. It is a system that works while you sleep.

Next up: Gold Tier — full autonomous decision making with multi-agent orchestration.

Stay tuned.

#BuildInPublic #AIEmployee #StartupLife #Automation #SilverTier"""
    },

    "industry_insight": {
        "description": "Share an insight about AI and the industry",
        "content": """\
Hot take: Most people are using AI wrong.

They treat it like a search engine — ask a question, get an answer, done.

The real power is in autonomous systems that:
1. Watch for events (new emails, tasks, signals)
2. Make decisions based on rules and context
3. Ask for human approval only when needed
4. Execute actions and log everything

That is an AI Employee — not an AI assistant.

The difference?
- Assistant waits for you
- Employee works while you sleep

Which one do you need?

#ArtificialIntelligence #AIStrategy #FutureOfWork #Automation #Leadership"""
    },

    "team_highlight": {
        "description": "Highlight the team or a collaborator",
        "content": """\
Behind every great system is a great team.

Building an AI Employee from scratch taught me more about systems thinking than any course ever did.

Key lessons:
- Start with the simplest version that works
- Add human oversight before automation
- Log everything — you will thank yourself later
- Test with mock data before touching production

Grateful for everyone who gave feedback, asked hard questions, and pushed the thinking forward.

We are just getting started.

#Teamwork #BuildInPublic #AIEmployee #GratefulLeader #Startups"""
    },

    "product_launch": {
        "description": "Announce a product or feature launch",
        "content": """\
It is live.

After weeks of building, testing, and iterating — our Silver Tier AI Employee is fully operational.

What it does today:
- Watches your Gmail for new tasks
- Plans and prioritizes automatically
- Asks for approval before taking action
- Sends real emails via Gmail SMTP
- Posts to LinkedIn (yes, this post was generated by it)

What it does not do:
- Replace human judgment
- Act without oversight
- Make decisions it should not make

Human-in-the-loop is not a limitation. It is the feature.

Try it. Break it. Tell me what you think.

#ProductLaunch #AIEmployee #HumanInTheLoop #Automation #BuildInPublic"""
    }
}


# ─── Core Logic ──────────────────────────────────────────────────────────────

def list_templates():
    """Print available templates."""
    print("\nAvailable LinkedIn Post Templates:")
    print("-" * 40)
    for name, data in TEMPLATES.items():
        print(f"  {name:<25} {data['description']}")
    print()
    print("Usage: python generate_post.py --template <name>")
    print()


def get_vault_path():
    """Resolve AI_Employee_Vault/Needs_Approval path from any working directory."""
    candidates = [
        Path(__file__).parent.parent.parent.parent / "AI_Employee_Vault" / "Needs_Approval",
        Path.cwd() / "AI_Employee_Vault" / "Needs_Approval",
        Path.cwd().parent / "AI_Employee_Vault" / "Needs_Approval",
    ]
    for path in candidates:
        parent = path.parent
        if parent.exists():
            path.mkdir(parents=True, exist_ok=True)
            return path
    # Fallback: create from cwd
    fallback = Path.cwd() / "AI_Employee_Vault" / "Needs_Approval"
    fallback.mkdir(parents=True, exist_ok=True)
    return fallback


def generate_approval_file(content, template_name="custom"):
    """
    Write post content to Needs_Approval as a structured approval request.

    Returns:
        Path: path to the created approval file
    """
    approval_dir = get_vault_path()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"linkedin_post_{timestamp}.md"
    filepath = approval_dir / filename

    approval_content = f"""# Approval Request: LinkedIn Post

**Action Type:** linkedin_post
**Template:** {template_name}
**Created:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Risk Level:** MEDIUM

---

## Post Content

**Content:**
{content}

---

## Manager Decision Required

To APPROVE, add this line:
```
DECISION: APPROVED
```

To REJECT, add this line:
```
DECISION: REJECTED
Reason: [your reason]
```

**Status:** Awaiting Decision
"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(approval_content)

    return filepath


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Generate LinkedIn post and send to approval queue"
    )
    parser.add_argument(
        "--template",
        choices=list(TEMPLATES.keys()),
        help="Use a built-in template"
    )
    parser.add_argument(
        "--custom",
        help="Provide your own post content"
    )
    parser.add_argument(
        "--topic",
        help="Topic hint to include in template (optional)"
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List available templates"
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Preview content without saving to approval"
    )

    args = parser.parse_args()

    # List templates
    if args.list:
        list_templates()
        return

    # Resolve content
    if args.custom:
        content = args.custom
        template_name = "custom"

    elif args.template:
        template_name = args.template
        content = TEMPLATES[template_name]["content"]
        if args.topic:
            content = f"Topic: {args.topic}\n\n" + content

    else:
        print("Error: provide --template <name> or --custom <text>")
        print("Run with --list to see available templates")
        sys.exit(1)

    # Preview mode
    if args.preview:
        print("\n" + "=" * 60)
        print("LINKEDIN POST PREVIEW")
        print("=" * 60)
        print(content)
        print("=" * 60)
        print("\nRun without --preview to send to approval queue.")
        return

    # Save to approval queue
    filepath = generate_approval_file(content, template_name)

    print(f"[GENERATED]  Template   : {template_name}")
    print(f"[SAVED]      File       : {filepath.name}")
    print(f"[LOCATION]   Folder     : AI_Employee_Vault/Needs_Approval/")
    print(f"[NEXT STEP]  Add 'DECISION: APPROVED' to the file, then run MCP executor")


if __name__ == "__main__":
    main()
